// A single error type carries an HTTP status, a stable machine-readable
// code (used by the frontend and in logs), and a user-safe message.
// Internal details (stack, Meta's raw error) travel separately in `debug`
// and are only ever written to logs, never sent to the client.

class AppError extends Error {
  constructor(code, message, status = 400, debug = null) {
    super(message);
    this.code = code;
    this.status = status;
    this.debug = debug;
  }
}

const ErrorCodes = {
  OAUTH_CANCELLED: 'OAUTH_CANCELLED',
  OAUTH_DENIED: 'OAUTH_DENIED',
  INVALID_CODE: 'INVALID_CODE',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ACCOUNT_NOT_AUTHORIZED: 'ACCOUNT_NOT_AUTHORIZED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  ACCOUNT_NOT_PROFESSIONAL: 'ACCOUNT_NOT_PROFESSIONAL',
  META_API_ERROR: 'META_API_ERROR',
  TIMEOUT: 'TIMEOUT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  NOT_FOUND: 'NOT_FOUND',
  INSTAGRAM_AUTH_FAILED: 'INSTAGRAM_AUTH_FAILED',

  // Phase 2.1 - media uploads
  NO_FILE_UPLOADED: 'NO_FILE_UPLOADED',
  INVALID_MEDIA_TYPE: 'INVALID_MEDIA_TYPE',
  MEDIA_TOO_LARGE: 'MEDIA_TOO_LARGE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',
  MEDIA_NOT_FOUND: 'MEDIA_NOT_FOUND',

  // Phase 2.1 - scheduled posts
  POST_NOT_FOUND: 'POST_NOT_FOUND',
  POST_INVALID_STATE: 'POST_INVALID_STATE',
  POST_NOT_EDITABLE: 'POST_NOT_EDITABLE',
  INVALID_POST_TYPE: 'INVALID_POST_TYPE',
  INVALID_MEDIA_COUNT: 'INVALID_MEDIA_COUNT',
  INVALID_MEDIA_FOR_POST_TYPE: 'INVALID_MEDIA_FOR_POST_TYPE',
  INVALID_SCHEDULE_TIME: 'INVALID_SCHEDULE_TIME',
  INSTAGRAM_ACCOUNT_NOT_FOUND: 'INSTAGRAM_ACCOUNT_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Phase 2.2a - publish worker
  INSTAGRAM_PUBLISH_FAILED: 'INSTAGRAM_PUBLISH_FAILED',
  INSTAGRAM_MEDIA_ERROR: 'INSTAGRAM_MEDIA_ERROR',
  INSTAGRAM_MEDIA_TIMEOUT: 'INSTAGRAM_MEDIA_TIMEOUT',
  UNSUPPORTED_POST_TYPE: 'UNSUPPORTED_POST_TYPE',

  // Phase 3.1 - authentication and invites
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVITE_REQUIRED: 'INVITE_REQUIRED',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
};

module.exports = { AppError, ErrorCodes };